### ISSUE TITLE
Like the concept…

### ISSUE THREAD

**Issue by duxswhatdux** [funny-cat-happy/joplin-plugin-TimelineRender#1]
Hi and thank you. 
I wanted to ask:
It appears the orange dot colour triggers to when it's that date.
- Has there been a thought to have a third colour for future date compared to past and current date? Green for past, orange for current, red for dates past current date?

Second, the date format used.
- It looks like its  yyyy-m-d as opposed to -mm-dd....a little confusing.
- Should it be using the the Date format I have set in Joplin Settings> General> Date Format?
- Is there consideration to have advance settings under Settings Plugins in the future for date format, dot colour management, other items that come to kind?
- That is for example, the plug-in called DDDot has its own set of configurations allowed beyond just the install of the plug-in. 
- - Not sure why the render date is opposite to your sample, a bit more confusing. I'm using linux, General date format is mm/dd/yyyy
- Even if I change it to yyyy-mm-dd, the render doesn't change 
![reverse date render to configured](https://user-images.githubusercontent.com/45373146/217130101-c74ab94b-f84c-412a-a33b-ec9b782979fd.png)

Any plans to make this so it renders with the IOS or Android app?

Thank you

**Comment by funny-cat-happy** [comment]
Hello,
Thank you for your feedback.I have solved your problem.
For your first  problem,I have add the feature to my plugin.You can download it from my github or offical site.
For your second problem,It is my fault.Different country has different way of displaying time.Now I have standardized the format.The format is yyyy-mm-dd.
About dot colour management,you can read my new readme in github.
As for rendering with the IOS or Android app,it is not my duty.In https://discourse.joplinapp.org/t/adding-plugins-on-android/27299 ,all plugins don't support for app and only in pc.
If you have other question,you can contact me.
