### ISSUE TITLE
request for change - enable hyperlink to other note

### ISSUE THREAD

**Issue by sve773** [funny-cat-happy/joplin-plugin-TimelineRender#3]
Dear funny-cat-happy,

You developed a great extension for Joplin. You have the same design feeling, like I to get an overview of a chronological process.
I would ask you, to modify your code to enable doc-links. It would be fine if we can use the standard Markdown link function, but instead the full qualified link name, like _[1. Welcome to Joplin! 🗒️](:/0fae6d2b85ea4dbc8b6b5fb993a50f58)_ only a small icon as placeholder should be visible, e.g. >>> or something you like.
The is not too much place in the timeline, so because of this I prefer to use it for a description or headline and not for the link information.

The motivation for this request is to use your tool for creating such as an overview document for other documents like an agenda or project main report etc. This will give Joplin more usability, parallel to groups by keyword or categories.

May you are so friendly and verified my request and found the time to bring this function in place.
Thanks a lot.

Best regards

**Comment by funny-cat-happy** [comment]
Do you mean you want to add a hyperlink to the timeline content and click it to jump to other note? like following:
````
```timeline
2023-1-1
>>>plan note
build project
build folder
```
````
render result is
![image](https://github.com/funny-cat-happy/joplin-plugin-TimelineRender/assets/53287533/20f93b26-02ac-4851-ad98-b8cb28fc7b3c)
then after clicking plan note, it can jump to the plan note.

**Comment by sve773** [comment]
Hi funny-cat-happy,

wow, this was a really fast response. Thanks a lot !!

Yes, your sample looks pretty good and fits well. Can I use the same link-word, like "_more details here_" or "_source_" for different entries? This is what I mean with Placeholder. The link behind the word "plan note" is unique bye the Note-ID, but the word itself isn't.

May I give you a hint? For inspiration for further development of your tool, have a look to the wordpress add-on "Timeline Express" [Demo](https://www.wp-timelineexpress.com/examples/basic-timeline/).

Again, thanks a lot for your help!
Regards,

Klaus

**Comment by funny-cat-happy** [comment]
After some try and code, I decide to give up the think. Because it goes against my original design.I just want to implement a simple timeline logging feature.This function is too complicated.I decided to develop another new plugin to achieve it. I also have to keep track of my project development progress according to a timeline.

**Comment by sve773** [comment]
Hello funny-cat-happy,

that's completely fine. You tried, and that's what counts. Good luck with the new project.
Regards,

Klaus
