### ISSUE TITLE
Markdown format in the text

### ISSUE THREAD

**Issue by Del95** [funny-cat-happy/joplin-plugin-TimelineRender#5]
Thanks a lot for developping this nice plugin.

I wish it could be possible to interpret also markdown in the text description of each milestone, like formatting, images, links to other notes... For now, it seems to render only plain text.

Thanks

**Comment by funny-cat-happy** [comment]
I don't fully understand your needs.Maybe you mean you can add images to timeline like following:
````
'''timeline
2023-1-1
![image](image link "image title")  
```
````
the result of rendering is
![image](https://github.com/funny-cat-happy/joplin-plugin-TimelineRender/assets/53287533/30cc48a4-b36d-4f67-adca-71f162b34879)
Or you can provide a picture to help describe.

**Comment by Del95** [comment]
Hello @funny-cat-happy ,

yes, this is what I mean for images.

Similarly, I would like to refer to some of my other notes.
Example:

```
'''timeline
2023-1-1
Some text bla blabla ![Title of my other note in my Joplin](:/azerty12345). Then the end of the text.
'''
```

Where `azerty12345` would be the ID to the note I want to refer to.
In the timeline, it would insert, within my text,  `Title of my other note in my Joplin` as a link to this other note.

And more generally, I wish I could enphasize some piece of text (e.g. bold, italics, etc) by using the usual Markdown syntax.

**Comment by funny-cat-happy** [comment]
The function of markdown is complete.And Linking functionality beyond what my plugin does.You can go to the plugin market and look for other people's plugins.
